
USE PAPELARIA;

CREATE VIEW BUSCAFUNCIONARIO AS
	SELECT NOMEFUNCIONARIO,MATRICULA 
		FROM FUNCIONARIO 
			WHERE FUNCAO = 'Vendedor';
        
select f.MATRICULA, F.NOMEFUNCIONARIO, F. FUNCAO
	FROM FUNCIONARIO F LEFT JOIN VENDAS V
        ON F.MATRICULA = v.MATRICULA
        WHERE V.MATRICULA IS NULL;
        
SELECT P.NOMEPRODUTO AS 'NOME DO PRODUTO', SUM(P.PRECO * LP.QNTVENDIDO) AS 'TOTAL',
	SUM(LP.QNTVENDIDO) AS 'QUANTIDADE'
		FROM PRODUTO P INNER JOIN LISTAPRODUTOS LP INNER JOIN CLIENTE
				ON P.CODIGO = LP.CODIGO
					GROUP BY P.NOMEPRODUTO;