USE CLINICA2;

DROP TABLE MEDICAMENTOPRES;
DROP TABLE RECEITA;
DROP TABLE CONSULTA;
DROP TABLE POSSUIESPECIALIDADE;
DROP TABLE ESPECIALIDADE;
DROP TABLE TELEFONE;
DROP TABLE PACIENTE;
DROP TABLE MEDICO;